"""AutoCore — lang.py
Centralized translations for all AutoCore modules.

Usage:
    from lang import t, set_lang, LANG
"""

_T = {
    "DA": {
        # ── main.py ───────────────────────────────────────────────────────────
        "banner":           "  AutoCore — Automatiseret Hackintosh USB-installer",
        "select_version":   "[2/6] Vælg macOS version:",
        "version_prompt":   "  Version [1-{n}]: ",
        "version_chosen":   "  macOS version valgt: {v}",
        "aborted":          "\n\n  Afbrudt.",
        "hw_fail":          "  ✗ Hardware-scanning fejlede. Afslutter.",
        "hw_issues_header": "  ┌─ HARDWARE-PROBLEMER ──────────────────────────────────────",
        "hw_issues_footer": "  └───────────────────────────────────────────────────────────",
        "hw_continue":      "  Hardware er muligvis ikke macOS-kompatibelt. Fortsæt alligevel? [j/N]: ",
        "hw_continue_key":  "j",
        "exiting":          "  Afslutter.",
        "kexts_failed":     "  ! {n} kexts fejlede — fortsætter uden: {names}",
        "efi_fail":         "  ✗ EFI-build fejlede. Afslutter.",
        "plist_fail":       "  ✗ config.plist generering fejlede. Afslutter.",
        "coresync_ready":   "  ✓ CoreSync.app klar — kopieres til USB og gemt på Skrivebordet\n",
        "done_title":       "  ║  ✓  AutoCore fuldført!                               ║",
        "done_next":        "  Hvad sker der nu:",
        "done_step1":       "  1. Sæt USB i din hackintosh og boot fra den (F12/Del/F2)",
        "done_step2":       "  2. Vælg 'Install macOS' i OpenCore-pickeren",
        "done_step3":       "  3. Installer macOS normalt",
        "done_step4":       "  4. Kør CoreSync.app (på USB) for at installere OpenCore",
        "done_step4b":      "     permanent på din harddisk",
        "flash_fail":       "  USB-flash annulleret eller fejlet.",
        "efi_available":    "  EFI-mappen er stadig tilgængelig i: {path}",
        "vm_warning":       "  ⚠  Kører i virtuel maskine — USB-adgang kan være upålidelig",
        "net_check":        "  Tjekker netværksforbindelse...",
        "net_ok":           "  ✓ Netværk OK",
        "net_fail":         "  ✗ Ingen netværksforbindelse — downloads vil fejle",
        "net_offline_warn": "  ⚠  Offline tilstand: kun kexts fra cache vil blive brugt.",
        "net_continue":     "  Fortsæt alligevel med cache-kexts? [j/N]: ",
        "net_continue_key": "j",
        "log_saved":        "  Log gemt til: {path}",
        "hw_report":        "  Hardware-rapport gemt til: {path}",
        "hw_json_saved":    "  Hardware JSON gemt til: {path}",
        "bios_title":       "  ┌─ BIOS-INDSTILLINGER (VIGTIGT) ─────────────────────────────",
        "bios_body": [
            "  │  Inden du booter fra USB — sæt disse indstillinger i BIOS:",
            "  │",
            "  │  ✓ Secure Boot          → Disabled",
            "  │  ✓ CSM / Legacy Boot    → Disabled  (ren UEFI)",
            "  │  ✓ VT-d                 → Disabled  (eller aktiver DisableIoMapper i OC)",
            "  │  ✓ CFG Lock             → Disabled  (hvis muligt)",
            "  │  ✓ XHCI Hand-off        → Enabled",
            "  │  ✓ Above 4G Decoding    → Enabled   (desktop: kræves for GPU)",
            "  │  ✓ DVMT Pre-Alloc       → 64 MB     (laptop: iGPU framebuffer)",
            "  │  ✓ Fast Boot            → Disabled",
            "  │  ✓ OS Type              → Other OS  (eller Windows UEFI)",
        ],
        "bios_footer":      "  └───────────────────────────────────────────────────────────",
        "update_found":     "  Eksisterende EFI fundet i: {path}",
        "update_choice":    "    [1] Opdater (ny OpenCore + kexts, bevar config.plist)\n    [2] Fuld build fra bunden",
        "update_prompt":    "  [1/2]: ",
        "update_mode":      "  → Kører i opdateringstilstand",
        "dry_run_notice":   "  [DRY-RUN] Ingen downloads, formatering eller USB-flash.",
        "dry_run_done":     "  [DRY-RUN] Scanning og valg fuldført. Afslutter.",
        "export_notice":    "  [EXPORT] EFI eksporteres til: {path}",
        "export_done":      "  [EXPORT] EFI klar på: {path}",
        # ── hardware.py ───────────────────────────────────────────────────────
        "scan_start":        "[1/6] Scanner hardware ({os})...",
        "scan_unknown_os":   "FEJL — ukendt OS",
        "hw_title":          "HARDWARE OVERSIGT",
        "hw_cores":          "Kerner",
        "hw_audio":          "Lyd (codec)",
        "hw_laptop":         "Laptop",
        "hw_macos_ok":       "macOS OK",
        "yes":               "Ja",
        "no":                "Nej",
        "hw_issues":         "PROBLEMER:",
        "hw_warnings":       "ADVARSLER:",
        "compat_nvidia":     "NVIDIA GPU — kun macOS op til High Sierra (10.13)",
        "compat_new_intel":  "12./13./14. gen Intel — kræver ekstra ACPI/Booter patches",
        "compat_amd_old":    "Ældre AMD CPU — meget begrænset macOS support",
        "compat_realtek_wifi":  "Realtek WiFi — ikke supporteret, kræver USB WiFi eller korterstatning",
        "compat_intel_wifi":    "Intel WiFi — virker med itlwm/AirportItlwm kext",
        "compat_broadcom_wifi": "Broadcom WiFi — tjek om kortmodellen er på kompatibilitetslisten",
        # ── kexts.py ──────────────────────────────────────────────────────────
        "kexts_selecting":   "[3/6] Vælger kexts til {v}...",
        "kexts_failed_dl":   "Følgende kexts fejlede: {names}",
        "kexts_all_ok":      "  ✓ Alle kexts downloadet til: {path}",
        "kexts_title":       "KEXTS — AUTOCORE VALG",
        "kexts_selected":    "{n} kexts valgt:",
        "kexts_tag_always":  "[altid]",
        "kexts_tag_hw":      "[hardware]",
        "kext_no_support":   "understøtter ikke",
        # ── usb.py ────────────────────────────────────────────────────────────
        "usb_no_drives":         "  ! Ingen USB-drev fundet (forventet 4–512 GB).",
        "usb_plug_in":           "  Tilslut en USB (min. 16 GB anbefalet) og prøv igen.",
        "usb_available":         "  USB-drev tilgængelige:",
        "usb_select_prompt":     "  Vælg USB [1-{n}]: ",
        "usb_invalid_choice":    "  Ugyldigt valg.",
        "usb_continue_small":    "  Fortsæt alligevel? [j/N]: ",
        "usb_continue_small_key":"j",
        "usb_confirm_delete":    "  ⚠  ADVARSEL: {device} ({name}, {size:.1f} GB) vil blive SLETTET!",
        "usb_confirm_prompt":    "  Skriv JA eller YES for at fortsætte: ",
        "usb_cancelled":         "  Annulleret.",
        "usb_eject":             "  → Skubber ud...",
        "usb_done":              "  ✓ USB klar!",
        "usb_next1":             "  → Tilslut USB til din hackintosh og vælg den i BIOS boot menu",
        "usb_next2":             "  → OpenCore picker vises — vælg 'Install macOS ...'",
        # ── config_plist.py ───────────────────────────────────────────────────
        "plist_generating":      "[5/6] Genererer config.plist...",
        "plist_not_found":       "  FEJL — sample.plist ikke fundet: {path}",
        "plist_title":           "CONFIG.PLIST — OVERSIGT",
        "plist_path_lbl":        "Sti",
        "plist_kexts_lbl":       "Kexts",
        "plist_next_steps":      "NÆSTE SKRIDT",
        "plist_serial_fallback": "Serial genereret med Python-fallback (Linux)",
        "plist_serial_tip":      "Til iMessage/iCloud: kør GenSMBIOS manuelt og opdater",
        "plist_serial_tip2":     "config.plist → PlatformInfo → Generic",
        "plist_ssdt_info_12":    "SSDTs: SSDT-PLUG-ALT + SSDT-EC-USBX tilføjet automatisk",
        "plist_ssdt_info_6":     "SSDTs: SSDT-EC-USBX + SSDT-PNLF tilføjet (tjek EFI/OC/ACPI/)",
        "plist_coverage_tip":    "Tjek Apple dækning for din serial (bør vise 'ugyldig'):",
        "macserial_unavail":     "  ⚠  macserial er ikke tilgængeligt på Linux — Python-fallback bruges til serial",
    },
    "EN": {
        # ── main.py ───────────────────────────────────────────────────────────
        "banner":           "  AutoCore — Automated Hackintosh USB Installer",
        "select_version":   "[2/6] Select macOS version:",
        "version_prompt":   "  Version [1-{n}]: ",
        "version_chosen":   "  macOS version selected: {v}",
        "aborted":          "\n\n  Aborted.",
        "hw_fail":          "  ✗ Hardware scan failed. Exiting.",
        "hw_issues_header": "  ┌─ HARDWARE ISSUES ─────────────────────────────────────────",
        "hw_issues_footer": "  └───────────────────────────────────────────────────────────",
        "hw_continue":      "  Hardware may not be macOS-compatible. Continue anyway? [y/N]: ",
        "hw_continue_key":  "y",
        "exiting":          "  Exiting.",
        "kexts_failed":     "  ! {n} kexts failed — continuing without: {names}",
        "efi_fail":         "  ✗ EFI build failed. Exiting.",
        "plist_fail":       "  ✗ config.plist generation failed. Exiting.",
        "coresync_ready":   "  ✓ CoreSync.app ready — copied to USB and saved to Desktop\n",
        "done_title":       "  ║  ✓  AutoCore complete!                               ║",
        "done_next":        "  What happens next:",
        "done_step1":       "  1. Plug USB into your hackintosh and boot from it (F12/Del/F2)",
        "done_step2":       "  2. Select 'Install macOS' in the OpenCore picker",
        "done_step3":       "  3. Install macOS normally",
        "done_step4":       "  4. Run CoreSync.app (on the USB) to install OpenCore",
        "done_step4b":      "     permanently onto your hard drive",
        "flash_fail":       "  USB flash cancelled or failed.",
        "efi_available":    "  EFI folder is still available at: {path}",
        "vm_warning":       "  ⚠  Running inside a virtual machine — USB access may be unreliable",
        "net_check":        "  Checking network connection...",
        "net_ok":           "  ✓ Network OK",
        "net_fail":         "  ✗ No network connection — downloads will fail",
        "net_offline_warn": "  ⚠  Offline mode: only cached kexts will be used.",
        "net_continue":     "  Continue anyway with cached kexts only? [y/N]: ",
        "net_continue_key": "y",
        "log_saved":        "  Log saved to: {path}",
        "hw_report":        "  Hardware report saved to: {path}",
        "hw_json_saved":    "  Hardware JSON saved to: {path}",
        "bios_title":       "  ┌─ BIOS SETTINGS (IMPORTANT) ────────────────────────────────",
        "bios_body": [
            "  │  Before booting from USB — set these options in BIOS:",
            "  │",
            "  │  ✓ Secure Boot          → Disabled",
            "  │  ✓ CSM / Legacy Boot    → Disabled  (pure UEFI)",
            "  │  ✓ VT-d                 → Disabled  (or enable DisableIoMapper in OC)",
            "  │  ✓ CFG Lock             → Disabled  (if available)",
            "  │  ✓ XHCI Hand-off        → Enabled",
            "  │  ✓ Above 4G Decoding    → Enabled   (desktop: required for GPU)",
            "  │  ✓ DVMT Pre-Alloc       → 64 MB     (laptop: iGPU framebuffer)",
            "  │  ✓ Fast Boot            → Disabled",
            "  │  ✓ OS Type              → Other OS  (or Windows UEFI)",
        ],
        "bios_footer":      "  └───────────────────────────────────────────────────────────",
        "update_found":     "  Existing EFI found at: {path}",
        "update_choice":    "    [1] Update (new OpenCore + kexts, keep config.plist)\n    [2] Full build from scratch",
        "update_prompt":    "  [1/2]: ",
        "update_mode":      "  → Running in update mode",
        "dry_run_notice":   "  [DRY-RUN] No downloads, formatting, or USB flashing.",
        "dry_run_done":     "  [DRY-RUN] Scan and selection complete. Exiting.",
        "export_notice":    "  [EXPORT] Exporting EFI to: {path}",
        "export_done":      "  [EXPORT] EFI ready at: {path}",
        # ── hardware.py ───────────────────────────────────────────────────────
        "scan_start":        "[1/6] Scanning hardware ({os})...",
        "scan_unknown_os":   "ERROR — unknown OS",
        "hw_title":          "HARDWARE SUMMARY",
        "hw_cores":          "Cores",
        "hw_audio":          "Audio (codec)",
        "hw_laptop":         "Laptop",
        "hw_macos_ok":       "macOS OK",
        "yes":               "Yes",
        "no":                "No",
        "hw_issues":         "ISSUES:",
        "hw_warnings":       "WARNINGS:",
        "compat_nvidia":     "NVIDIA GPU — macOS High Sierra (10.13) max",
        "compat_new_intel":  "Gen 12/13/14 Intel — requires extra ACPI/Booter patches",
        "compat_amd_old":    "Old AMD CPU — very limited macOS support",
        "compat_realtek_wifi":  "Realtek WiFi — not supported, requires USB WiFi or card replacement",
        "compat_intel_wifi":    "Intel WiFi — works with itlwm/AirportItlwm kext",
        "compat_broadcom_wifi": "Broadcom WiFi — check if your card model is on the compatibility list",
        # ── kexts.py ──────────────────────────────────────────────────────────
        "kexts_selecting":   "[3/6] Selecting kexts for {v}...",
        "kexts_failed_dl":   "Following kexts failed: {names}",
        "kexts_all_ok":      "  ✓ All kexts downloaded to: {path}",
        "kexts_title":       "KEXTS — AUTOCORE SELECTION",
        "kexts_selected":    "{n} kexts selected:",
        "kexts_tag_always":  "[always]",
        "kexts_tag_hw":      "[hardware]",
        "kext_no_support":   "does not support",
        # ── usb.py ────────────────────────────────────────────────────────────
        "usb_no_drives":         "  ! No USB drives found (expected 4–512 GB).",
        "usb_plug_in":           "  Connect a USB (min. 16 GB recommended) and try again.",
        "usb_available":         "  Available USB drives:",
        "usb_select_prompt":     "  Select USB [1-{n}]: ",
        "usb_invalid_choice":    "  Invalid choice.",
        "usb_continue_small":    "  Continue anyway? [y/N]: ",
        "usb_continue_small_key":"y",
        "usb_confirm_delete":    "  ⚠  WARNING: {device} ({name}, {size:.1f} GB) will be DELETED!",
        "usb_confirm_prompt":    "  Type JA or YES to continue: ",
        "usb_cancelled":         "  Cancelled.",
        "usb_eject":             "  → Ejecting...",
        "usb_done":              "  ✓ USB ready!",
        "usb_next1":             "  → Plug USB into your hackintosh and select it in the BIOS boot menu",
        "usb_next2":             "  → OpenCore picker will appear — select 'Install macOS ...'",
        # ── config_plist.py ───────────────────────────────────────────────────
        "plist_generating":      "[5/6] Generating config.plist...",
        "plist_not_found":       "  ERROR — sample.plist not found: {path}",
        "plist_title":           "CONFIG.PLIST — SUMMARY",
        "plist_path_lbl":        "Path",
        "plist_kexts_lbl":       "Kexts",
        "plist_next_steps":      "NEXT STEPS",
        "plist_serial_fallback": "Serial generated with Python-fallback (Linux)",
        "plist_serial_tip":      "For iMessage/iCloud: run GenSMBIOS manually and update",
        "plist_serial_tip2":     "config.plist → PlatformInfo → Generic",
        "plist_ssdt_info_12":    "SSDTs: SSDT-PLUG-ALT + SSDT-EC-USBX added automatically",
        "plist_ssdt_info_6":     "SSDTs: SSDT-EC-USBX + SSDT-PNLF added (check EFI/OC/ACPI/)",
        "plist_coverage_tip":    "Check Apple coverage for your serial (should show 'invalid'):",
        "macserial_unavail":     "  ⚠  macserial is unavailable on Linux — Python fallback will be used for serial",
    },
}

LANG = "DA"


def t(key, **kwargs):
    """Return translated string for the current language."""
    s = _T[LANG].get(key, _T["EN"].get(key, key))
    if isinstance(s, list):
        return [line.format(**kwargs) for line in s] if kwargs else s
    return s.format(**kwargs) if kwargs else s


def set_lang(lang):
    """Set the global language (e.g. 'DA' or 'EN')."""
    global LANG
    if lang in _T:
        LANG = lang
